
[terminal.shell]
program = "/run/current-system/sw/bin/zsh"
args = ["-c", "tmux attach || tmux"]

[window]
padding = { x = 10, y = 10 }
opacity = 0.9

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
size = 16.0

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 600

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[general]
import = [
    "~/.config/alacritty/hojicha.toml",
]

[terminal]
