[theme]
theme = "gruvbox-dark"
[theme.overrides]
separator = ""

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
[block.theme_overrides]
idle_bg = "#98971a"
info_bg = "#d79921"
warning_bg = "#d65d0e"
critical_bg = "#cc241d"

[[block]]
block = "memory"
[block.theme_overrides]
idle_bg = "#98971a"

[[block]]
block = "nvidia_gpu"
[block.theme_overrides]
idle_bg = "#98971a"

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "music"

[[block]]
block = "net"

[[block]]
block = "keyboard_layout"

[[block]]
block = "time"

